
include: package:flutter_lints/flutter.yaml

linter:
  rules:
    file_names: false
    avoid_print: false
    camel_case_types: false
    non_constant_identifier_names: false
    prefer_const_constructors: false
    curly_braces_in_flow_control_structures: false
    use_key_in_widget_constructors: false
    prefer_const_literals_to_create_immutables: false
    prefer_const_constructors_in_immutables: false
    no_logic_in_create_state: false

