// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBJGoSxQvYnj5VOXXygLkJxUDsRqo8gPbw',
    appId: '1:382204423603:web:331239de06cb8e8b916fc6',
    messagingSenderId: '382204423603',
    projectId: 'apptex-chat',
    authDomain: 'apptex-chat.firebaseapp.com',
    storageBucket: 'apptex-chat.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvK30aJfXrbAxK4i2dxFuMdGbrW46Sq6Y',
    appId: '1:382204423603:android:e2bcba81c1e03ced916fc6',
    messagingSenderId: '382204423603',
    projectId: 'apptex-chat',
    storageBucket: 'apptex-chat.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCpEyu-RzlGn2ZI-Y1K2_Jb7MLyRrrYt60',
    appId: '1:382204423603:ios:dd801c6c6ab12c2e916fc6',
    messagingSenderId: '382204423603',
    projectId: 'apptex-chat',
    storageBucket: 'apptex-chat.appspot.com',
    iosClientId: '382204423603-99j8m4hsim70g270l8g5civg10f8d1qp.apps.googleusercontent.com',
    iosBundleId: 'com.apptex.chat',
  );
}
